# theme: minima
author:
  name: Andreas Nicklaus
  email: me@andreasnicklaus.de

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: dark

  social_links:
      - platform: github
        user_url: https://github.com/andreasnicklaus
      - platform: instagram
        user_url: https://www.instagram.com/andreasnicklaus
      - platform: linkedin
        user_url: https://www.linkedin.com/in/andreasnicklaus
      - platform: twitter
        user_url: https://twitter.com/AndreasNicklaus