name: readMeUpdate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dateUpdate:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: echo date
        run: echo ${{ steps.date.outputs.date }}

      - name: Find and Replace date in readME.md
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{date}}"
          replace: ${{ steps.date.outputs.date }}
          include: ./readME.md

      - name: Print readMe.md content
        run: cat ./readMe.md

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}